# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: EKGF Data Product Workgroup
site_description: The EKGF Data Product Workgroup, defining standards for Semantic Data Products
repo_name: 'EKGF/data-product'
repo_url: https://github.com/EKGF/data-product
site_url: https://data-product.ekgf.org
edit_uri: edit/main/docs/
site_dir: site
site_author: Enterprise Knowledge Graph Foundation
copyright: Copyright &copy; 2019-2023 Enterprise Knowledge Graph Foundation

# Navigation
# nav: omitted, because we're using the awesome-pages plugin (https://squidfunk.github.io/mkdocs-material/plugins/awesome-pages/)
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  language: en
  custom_dir: docs-overrides/
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: ekgf-logo-symbol
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: light-blue
      toggle:
#        icon: material/toggle-switch-off-outline
#        icon: material/lightbulb-outline
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep orange
      toggle:
#        icon: material/toggle-switch
#        icon: material/lightbulb
        icon: material/weather-night
        name: Switch to light mode
  features:
    - search.highlight
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
#    - navigation.sections
#    - navigation.expand
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - content.code.annotate
extra:
  homepage: https://www.ekgf.org/quadrants
  generator: false
  giscus:
    repo_id: 'R_kgDOJPPZTA'
    category:
      name: 'General'
      id: 'DIC_kwDOJPPZTM4CVxUx'
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/EKG_Foundation
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/EKGF
    - icon: fontawesome/brands/github
      link: https://github.com/EKGF/data-product
  analytics:
    provider: google
    property: G-9LCW4TSSRP
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
extra_javascript:
  - "javascript/images_dark.js"
  - "javascript/refresh_on_toggle_dark_light.js"
  - "https://cdn.jsdelivr.net/gh/rod2ik/cdn@main/mkdocs/javascripts/mkdocs-graphviz.js"
plugins:
  - include-markdown
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      locale: en
      type: timeago
      timezone: America/New_York
      exclude:
        - pillar/*
  - search:
      lang:
        - en
  - exclude-search:
      exclude:
        - 'fragment/*'
  - build_plantuml:
      render: "server" # or "local" for local rendering
      bin_path: "/usr/local/bin/plantuml" # ignored when render: server
      server: "http://www.plantuml.com/plantuml" # official plantuml server
      output_format: "svg" # or "png"
      diagram_root: "docs/diagrams" # should reside under docs_dir
      output_folder: "out"
      input_folder: "src"
      input_extensions: "" # comma separated list of extensions to parse, by default every file is parsed
      theme_enabled: true
      theme_folder: "include/themes"
      theme_light: "light.puml"
      theme_dark: "dark.puml"
  - awesome-pages:
      filename: .pages.yaml
      collapse_single_pages: false
      strict: true
  - exclude:
      glob:
        - "*.tmp"
        - "*.sparql"
        - "*.gz"
        - 'diagrams/src/*'
        - 'fragment/*'
      regex:
        - '.*\.(tmp|bin|tar)$'
        - '_.*\.md$'
#  - kroki:
#      ServerURL: https://kroki.io/
#      DownloadImages: false
#      DownloadDir: docs/diagrams/out
#  - with-pdf:
#      author: The Team
#      copyright: Copyright &copy; 2018 - 2022 agnos.ai UK Ltd & Stealth Software Technologies, Inc --- Confidential
#      cover: true
#      back_cover: false
#      cover_title: The Datapoint Protocol
#      cover_subtitle: Pitch, Business Plan & Proposal
#      #custom_template_path: TEMPLATES PATH
#      toc_title: Table of Contents
#      heading_shift: false
#      toc_level: 1
#      ordered_chapter_level: 3
#      #excludes_children:
#        #    - 'release-notes/:upgrading'
#        #    - 'release-notes/:changelog'
#        #
#      exclude_pages:
#        - pdf.md
#        #convert_iframe:
#        #    - src: IFRAME SRC
#        #      img: POSTER IMAGE URL
#        #      text: ALTERNATE TEXT
#        #    - src: ...
#        #two_columns_level: 3
#      output_path: assets/datapoint-protocol.pdf
#      enabled_if_env: ENABLE_PDF_EXPORT
#      debug_html: false
#      show_anchors: false
#      verbose: false
#      render_js: false
#      strict: false
#      #headless_chrome_path: headless-chromium
#      #

markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - meta
# - mdx_spanner
  - def_list
  - abbr
  - admonition
# - mdx_emdash (causes too many warnings)
  - footnotes
  - tables
  - mkdocs_graphviz
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path:
        - .
        - docs
      check_paths: true
      auto_append:
        - abbreviations.md
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
